// Current-squad pool (~2025–26 season) for the friendly auction game.
// Position = primary auction position: GK | DEF | MID | ATT.
// `value` = approximate current market value in €m (Transfermarkt-style),
// used to judge each sale as a steal / fair / overpay.
// `note` flags recent arrivals / loans so bidders have context.

export type Position = 'GK' | 'DEF' | 'MID' | 'ATT';

export interface Player {
  id: string;
  name: string;
  club: string;
  position: Position;
  value: number;
  note?: string;
}

export const CLUBS = [
  'Chelsea',
  'Arsenal',
  'Newcastle',
  'Liverpool',
  'Manchester City',
  'Manchester United',
  'Barcelona',
  'Real Madrid',
  'Atletico Madrid',
  'PSG',
  'Bayern Munich',
] as const;

// Raw list grouped by club; ids are generated below so we never hand-maintain them.
const RAW: Omit<Player, 'id'>[] = [
  // Chelsea
  { name: 'Robert Sánchez', club: 'Chelsea', position: 'GK', value: 18 },
  { name: 'Filip Jørgensen', club: 'Chelsea', position: 'GK', value: 12 },
  { name: 'Levi Colwill', club: 'Chelsea', position: 'DEF', value: 55 },
  { name: 'Wesley Fofana', club: 'Chelsea', position: 'DEF', value: 30 },
  { name: 'Tosin Adarabioyo', club: 'Chelsea', position: 'DEF', value: 25 },
  { name: 'Benoît Badiashile', club: 'Chelsea', position: 'DEF', value: 28 },
  { name: 'Marc Cucurella', club: 'Chelsea', position: 'DEF', value: 45 },
  { name: 'Reece James', club: 'Chelsea', position: 'DEF', value: 45 },
  { name: 'Malo Gusto', club: 'Chelsea', position: 'DEF', value: 45 },
  { name: 'Trevoh Chalobah', club: 'Chelsea', position: 'DEF', value: 22 },
  { name: 'Enzo Fernández', club: 'Chelsea', position: 'MID', value: 75 },
  { name: 'Moisés Caicedo', club: 'Chelsea', position: 'MID', value: 90 },
  { name: 'Roméo Lavia', club: 'Chelsea', position: 'MID', value: 40 },
  { name: 'Cole Palmer', club: 'Chelsea', position: 'MID', value: 130 },
  { name: 'Dário Essugo', club: 'Chelsea', position: 'MID', value: 18 },
  { name: 'Nicolas Jackson', club: 'Chelsea', position: 'ATT', value: 55 },
  { name: 'Pedro Neto', club: 'Chelsea', position: 'ATT', value: 50 },
  { name: 'Christopher Nkunku', club: 'Chelsea', position: 'ATT', value: 45 },
  { name: 'João Pedro', club: 'Chelsea', position: 'ATT', value: 60, note: "new '25" },
  { name: 'Liam Delap', club: 'Chelsea', position: 'ATT', value: 45, note: "new '25" },
  { name: 'Estêvão', club: 'Chelsea', position: 'ATT', value: 60, note: "new '25" },
  { name: 'Jamie Gittens', club: 'Chelsea', position: 'ATT', value: 45, note: "new '25" },

  // Arsenal
  { name: 'David Raya', club: 'Arsenal', position: 'GK', value: 35 },
  { name: 'Kepa Arrizabalaga', club: 'Arsenal', position: 'GK', value: 8 },
  { name: 'William Saliba', club: 'Arsenal', position: 'DEF', value: 80 },
  { name: 'Gabriel Magalhães', club: 'Arsenal', position: 'DEF', value: 70 },
  { name: 'Ben White', club: 'Arsenal', position: 'DEF', value: 45 },
  { name: 'Jurriën Timber', club: 'Arsenal', position: 'DEF', value: 55 },
  { name: 'Riccardo Calafiori', club: 'Arsenal', position: 'DEF', value: 45 },
  { name: 'Myles Lewis-Skelly', club: 'Arsenal', position: 'DEF', value: 50 },
  { name: 'Cristhian Mosquera', club: 'Arsenal', position: 'DEF', value: 30, note: "new '25" },
  { name: 'Declan Rice', club: 'Arsenal', position: 'MID', value: 110 },
  { name: 'Martin Ødegaard', club: 'Arsenal', position: 'MID', value: 90 },
  { name: 'Mikel Merino', club: 'Arsenal', position: 'MID', value: 45 },
  { name: 'Martín Zubimendi', club: 'Arsenal', position: 'MID', value: 65, note: "new '25" },
  { name: 'Ethan Nwaneri', club: 'Arsenal', position: 'MID', value: 45 },
  { name: 'Bukayo Saka', club: 'Arsenal', position: 'ATT', value: 140 },
  { name: 'Gabriel Martinelli', club: 'Arsenal', position: 'ATT', value: 60 },
  { name: 'Kai Havertz', club: 'Arsenal', position: 'ATT', value: 65 },
  { name: 'Leandro Trossard', club: 'Arsenal', position: 'ATT', value: 35 },
  { name: 'Gabriel Jesus', club: 'Arsenal', position: 'ATT', value: 45 },
  { name: 'Viktor Gyökeres', club: 'Arsenal', position: 'ATT', value: 75, note: "new '25" },
  { name: 'Noni Madueke', club: 'Arsenal', position: 'ATT', value: 45, note: "new '25" },
  { name: 'Eberechi Eze', club: 'Arsenal', position: 'ATT', value: 65, note: "new '25" },

  // Newcastle
  { name: 'Nick Pope', club: 'Newcastle', position: 'GK', value: 12 },
  { name: 'Aaron Ramsdale', club: 'Newcastle', position: 'GK', value: 18, note: "new '25" },
  { name: 'Martin Dúbravka', club: 'Newcastle', position: 'GK', value: 4 },
  { name: 'Kieran Trippier', club: 'Newcastle', position: 'DEF', value: 8 },
  { name: 'Sven Botman', club: 'Newcastle', position: 'DEF', value: 40 },
  { name: 'Fabian Schär', club: 'Newcastle', position: 'DEF', value: 10 },
  { name: 'Dan Burn', club: 'Newcastle', position: 'DEF', value: 8 },
  { name: 'Tino Livramento', club: 'Newcastle', position: 'DEF', value: 45 },
  { name: 'Lewis Hall', club: 'Newcastle', position: 'DEF', value: 40 },
  { name: 'Malick Thiaw', club: 'Newcastle', position: 'DEF', value: 35, note: "new '25" },
  { name: 'Bruno Guimarães', club: 'Newcastle', position: 'MID', value: 85 },
  { name: 'Sandro Tonali', club: 'Newcastle', position: 'MID', value: 55 },
  { name: 'Joelinton', club: 'Newcastle', position: 'MID', value: 45 },
  { name: 'Joe Willock', club: 'Newcastle', position: 'MID', value: 25 },
  { name: 'Lewis Miley', club: 'Newcastle', position: 'MID', value: 30 },
  { name: 'Jacob Ramsey', club: 'Newcastle', position: 'MID', value: 35, note: "new '25" },
  { name: 'Anthony Gordon', club: 'Newcastle', position: 'ATT', value: 65 },
  { name: 'Harvey Barnes', club: 'Newcastle', position: 'ATT', value: 40 },
  { name: 'Jacob Murphy', club: 'Newcastle', position: 'ATT', value: 22 },
  { name: 'Anthony Elanga', club: 'Newcastle', position: 'ATT', value: 55, note: "new '25" },
  { name: 'Nick Woltemade', club: 'Newcastle', position: 'ATT', value: 50, note: "new '25" },
  { name: 'Yoane Wissa', club: 'Newcastle', position: 'ATT', value: 35, note: "new '25" },

  // Liverpool
  { name: 'Alisson', club: 'Liverpool', position: 'GK', value: 30 },
  { name: 'Giorgi Mamardashvili', club: 'Liverpool', position: 'GK', value: 30, note: "new '25" },
  { name: 'Virgil van Dijk', club: 'Liverpool', position: 'DEF', value: 25 },
  { name: 'Ibrahima Konaté', club: 'Liverpool', position: 'DEF', value: 60 },
  { name: 'Andy Robertson', club: 'Liverpool', position: 'DEF', value: 18 },
  { name: 'Conor Bradley', club: 'Liverpool', position: 'DEF', value: 45 },
  { name: 'Milos Kerkez', club: 'Liverpool', position: 'DEF', value: 45, note: "new '25" },
  { name: 'Jeremie Frimpong', club: 'Liverpool', position: 'DEF', value: 40, note: "new '25" },
  { name: 'Alexis Mac Allister', club: 'Liverpool', position: 'MID', value: 90 },
  { name: 'Dominik Szoboszlai', club: 'Liverpool', position: 'MID', value: 85 },
  { name: 'Ryan Gravenberch', club: 'Liverpool', position: 'MID', value: 75 },
  { name: 'Curtis Jones', club: 'Liverpool', position: 'MID', value: 50 },
  { name: 'Wataru Endo', club: 'Liverpool', position: 'MID', value: 12 },
  { name: 'Florian Wirtz', club: 'Liverpool', position: 'MID', value: 130, note: "new '25" },
  { name: 'Mohamed Salah', club: 'Liverpool', position: 'ATT', value: 55 },
  { name: 'Cody Gakpo', club: 'Liverpool', position: 'ATT', value: 65 },
  { name: 'Federico Chiesa', club: 'Liverpool', position: 'ATT', value: 20 },
  { name: 'Hugo Ekitiké', club: 'Liverpool', position: 'ATT', value: 75, note: "new '25" },
  { name: 'Alexander Isak', club: 'Liverpool', position: 'ATT', value: 120, note: "new '25" },

  // Manchester City
  { name: 'Gianluigi Donnarumma', club: 'Manchester City', position: 'GK', value: 35, note: "new '25" },
  { name: 'Ederson', club: 'Manchester City', position: 'GK', value: 20 },
  { name: 'Stefan Ortega', club: 'Manchester City', position: 'GK', value: 10 },
  { name: 'James Trafford', club: 'Manchester City', position: 'GK', value: 30, note: "new '25" },
  { name: 'Rúben Dias', club: 'Manchester City', position: 'DEF', value: 70 },
  { name: 'John Stones', club: 'Manchester City', position: 'DEF', value: 30 },
  { name: 'Nathan Aké', club: 'Manchester City', position: 'DEF', value: 30 },
  { name: 'Manuel Akanji', club: 'Manchester City', position: 'DEF', value: 35 },
  { name: 'Joško Gvardiol', club: 'Manchester City', position: 'DEF', value: 75 },
  { name: 'Rico Lewis', club: 'Manchester City', position: 'DEF', value: 45 },
  { name: 'Abdukodir Khusanov', club: 'Manchester City', position: 'DEF', value: 30, note: "new '25" },
  { name: 'Rayan Aït-Nouri', club: 'Manchester City', position: 'DEF', value: 40, note: "new '25" },
  { name: 'Rodri', club: 'Manchester City', position: 'MID', value: 110 },
  { name: 'Bernardo Silva', club: 'Manchester City', position: 'MID', value: 50 },
  { name: 'İlkay Gündoğan', club: 'Manchester City', position: 'MID', value: 10 },
  { name: 'Mateo Kovačić', club: 'Manchester City', position: 'MID', value: 30 },
  { name: 'Tijjani Reijnders', club: 'Manchester City', position: 'MID', value: 70, note: "new '25" },
  { name: 'Rayan Cherki', club: 'Manchester City', position: 'MID', value: 50, note: "new '25" },
  { name: 'Nico González', club: 'Manchester City', position: 'MID', value: 50 },
  { name: 'Erling Haaland', club: 'Manchester City', position: 'ATT', value: 180 },
  { name: 'Phil Foden', club: 'Manchester City', position: 'ATT', value: 110 },
  { name: 'Jérémy Doku', club: 'Manchester City', position: 'ATT', value: 60 },
  { name: 'Savinho', club: 'Manchester City', position: 'ATT', value: 60 },
  { name: 'Omar Marmoush', club: 'Manchester City', position: 'ATT', value: 60 },

  // Manchester United
  { name: 'André Onana', club: 'Manchester United', position: 'GK', value: 25 },
  { name: 'Altay Bayındır', club: 'Manchester United', position: 'GK', value: 10 },
  { name: 'Senne Lammens', club: 'Manchester United', position: 'GK', value: 18, note: "new '25" },
  { name: 'Lisandro Martínez', club: 'Manchester United', position: 'DEF', value: 45 },
  { name: 'Matthijs de Ligt', club: 'Manchester United', position: 'DEF', value: 40 },
  { name: 'Harry Maguire', club: 'Manchester United', position: 'DEF', value: 15 },
  { name: 'Luke Shaw', club: 'Manchester United', position: 'DEF', value: 18 },
  { name: 'Diogo Dalot', club: 'Manchester United', position: 'DEF', value: 35 },
  { name: 'Noussair Mazraoui', club: 'Manchester United', position: 'DEF', value: 35 },
  { name: 'Leny Yoro', club: 'Manchester United', position: 'DEF', value: 55 },
  { name: 'Bruno Fernandes', club: 'Manchester United', position: 'MID', value: 60 },
  { name: 'Casemiro', club: 'Manchester United', position: 'MID', value: 12 },
  { name: 'Kobbie Mainoo', club: 'Manchester United', position: 'MID', value: 65 },
  { name: 'Manuel Ugarte', club: 'Manchester United', position: 'MID', value: 45 },
  { name: 'Mason Mount', club: 'Manchester United', position: 'MID', value: 30 },
  { name: 'Joshua Zirkzee', club: 'Manchester United', position: 'ATT', value: 35 },
  { name: 'Amad Diallo', club: 'Manchester United', position: 'ATT', value: 45 },
  { name: 'Bryan Mbeumo', club: 'Manchester United', position: 'ATT', value: 65, note: "new '25" },
  { name: 'Matheus Cunha', club: 'Manchester United', position: 'ATT', value: 60, note: "new '25" },
  { name: 'Benjamin Šeško', club: 'Manchester United', position: 'ATT', value: 75, note: "new '25" },

  // Barcelona
  { name: 'Marc-André ter Stegen', club: 'Barcelona', position: 'GK', value: 12 },
  { name: 'Joan García', club: 'Barcelona', position: 'GK', value: 30, note: "new '25" },
  { name: 'Wojciech Szczęsny', club: 'Barcelona', position: 'GK', value: 2 },
  { name: 'Ronald Araújo', club: 'Barcelona', position: 'DEF', value: 65 },
  { name: 'Pau Cubarsí', club: 'Barcelona', position: 'DEF', value: 80 },
  { name: 'Jules Koundé', club: 'Barcelona', position: 'DEF', value: 65 },
  { name: 'Alejandro Balde', club: 'Barcelona', position: 'DEF', value: 55 },
  { name: 'Iñigo Martínez', club: 'Barcelona', position: 'DEF', value: 12 },
  { name: 'Andreas Christensen', club: 'Barcelona', position: 'DEF', value: 18 },
  { name: 'Pedri', club: 'Barcelona', position: 'MID', value: 140 },
  { name: 'Frenkie de Jong', club: 'Barcelona', position: 'MID', value: 60 },
  { name: 'Gavi', club: 'Barcelona', position: 'MID', value: 80 },
  { name: 'Fermín López', club: 'Barcelona', position: 'MID', value: 60 },
  { name: 'Dani Olmo', club: 'Barcelona', position: 'MID', value: 60 },
  { name: 'Marc Casadó', club: 'Barcelona', position: 'MID', value: 40 },
  { name: 'Marc Bernal', club: 'Barcelona', position: 'MID', value: 25 },
  { name: 'Robert Lewandowski', club: 'Barcelona', position: 'ATT', value: 15 },
  { name: 'Lamine Yamal', club: 'Barcelona', position: 'ATT', value: 200 },
  { name: 'Raphinha', club: 'Barcelona', position: 'ATT', value: 100 },
  { name: 'Ferran Torres', club: 'Barcelona', position: 'ATT', value: 35 },
  { name: 'Marcus Rashford', club: 'Barcelona', position: 'ATT', value: 35, note: "loan '25" },

  // Real Madrid
  { name: 'Thibaut Courtois', club: 'Real Madrid', position: 'GK', value: 20 },
  { name: 'Andriy Lunin', club: 'Real Madrid', position: 'GK', value: 18 },
  { name: 'Antonio Rüdiger', club: 'Real Madrid', position: 'DEF', value: 18 },
  { name: 'Éder Militão', club: 'Real Madrid', position: 'DEF', value: 50 },
  { name: 'David Alaba', club: 'Real Madrid', position: 'DEF', value: 8 },
  { name: 'Dean Huijsen', club: 'Real Madrid', position: 'DEF', value: 60, note: "new '25" },
  { name: 'Trent Alexander-Arnold', club: 'Real Madrid', position: 'DEF', value: 70, note: "new '25" },
  { name: 'Ferland Mendy', club: 'Real Madrid', position: 'DEF', value: 15 },
  { name: 'Fran García', club: 'Real Madrid', position: 'DEF', value: 22 },
  { name: 'Raúl Asencio', club: 'Real Madrid', position: 'DEF', value: 30 },
  { name: 'Jude Bellingham', club: 'Real Madrid', position: 'MID', value: 180 },
  { name: 'Federico Valverde', club: 'Real Madrid', position: 'MID', value: 130 },
  { name: 'Aurélien Tchouaméni', club: 'Real Madrid', position: 'MID', value: 80 },
  { name: 'Eduardo Camavinga', club: 'Real Madrid', position: 'MID', value: 90 },
  { name: 'Arda Güler', club: 'Real Madrid', position: 'MID', value: 60 },
  { name: 'Dani Ceballos', club: 'Real Madrid', position: 'MID', value: 20 },
  { name: 'Franco Mastantuono', club: 'Real Madrid', position: 'MID', value: 45, note: "new '25" },
  { name: 'Kylian Mbappé', club: 'Real Madrid', position: 'ATT', value: 180 },
  { name: 'Vinícius Júnior', club: 'Real Madrid', position: 'ATT', value: 200 },
  { name: 'Rodrygo', club: 'Real Madrid', position: 'ATT', value: 100 },
  { name: 'Endrick', club: 'Real Madrid', position: 'ATT', value: 50 },
  { name: 'Brahim Díaz', club: 'Real Madrid', position: 'ATT', value: 35 },
  { name: 'Gonzalo García', club: 'Real Madrid', position: 'ATT', value: 30 },

  // Atletico Madrid
  { name: 'Jan Oblak', club: 'Atletico Madrid', position: 'GK', value: 20 },
  { name: 'Juan Musso', club: 'Atletico Madrid', position: 'GK', value: 6 },
  { name: 'José María Giménez', club: 'Atletico Madrid', position: 'DEF', value: 30 },
  { name: 'Robin Le Normand', club: 'Atletico Madrid', position: 'DEF', value: 35 },
  { name: 'Clément Lenglet', club: 'Atletico Madrid', position: 'DEF', value: 8 },
  { name: 'Nahuel Molina', club: 'Atletico Madrid', position: 'DEF', value: 30 },
  { name: 'Reinildo', club: 'Atletico Madrid', position: 'DEF', value: 8 },
  { name: 'David Hancko', club: 'Atletico Madrid', position: 'DEF', value: 40, note: "new '25" },
  { name: 'Matteo Ruggeri', club: 'Atletico Madrid', position: 'DEF', value: 30, note: "new '25" },
  { name: 'Koke', club: 'Atletico Madrid', position: 'MID', value: 8 },
  { name: 'Pablo Barrios', club: 'Atletico Madrid', position: 'MID', value: 50 },
  { name: 'Conor Gallagher', club: 'Atletico Madrid', position: 'MID', value: 45 },
  { name: 'Marcos Llorente', club: 'Atletico Madrid', position: 'MID', value: 40 },
  { name: 'Giuliano Simeone', club: 'Atletico Madrid', position: 'MID', value: 40 },
  { name: 'Johnny Cardoso', club: 'Atletico Madrid', position: 'MID', value: 30, note: "new '25" },
  { name: 'Thiago Almada', club: 'Atletico Madrid', position: 'MID', value: 45 },
  { name: 'Antoine Griezmann', club: 'Atletico Madrid', position: 'ATT', value: 25 },
  { name: 'Julián Álvarez', club: 'Atletico Madrid', position: 'ATT', value: 90 },
  { name: 'Alexander Sørloth', club: 'Atletico Madrid', position: 'ATT', value: 35 },
  { name: 'Giacomo Raspadori', club: 'Atletico Madrid', position: 'ATT', value: 30, note: "new '25" },

  // PSG
  { name: 'Lucas Chevalier', club: 'PSG', position: 'GK', value: 35, note: "new '25" },
  { name: 'Matvey Safonov', club: 'PSG', position: 'GK', value: 18 },
  { name: 'Marquinhos', club: 'PSG', position: 'DEF', value: 30 },
  { name: 'Willian Pacho', club: 'PSG', position: 'DEF', value: 60 },
  { name: 'Lucas Hernández', club: 'PSG', position: 'DEF', value: 25 },
  { name: 'Achraf Hakimi', club: 'PSG', position: 'DEF', value: 65 },
  { name: 'Nuno Mendes', club: 'PSG', position: 'DEF', value: 75 },
  { name: 'Lucas Beraldo', club: 'PSG', position: 'DEF', value: 30 },
  { name: 'Vitinha', club: 'PSG', position: 'MID', value: 90 },
  { name: 'João Neves', club: 'PSG', position: 'MID', value: 90 },
  { name: 'Fabián Ruiz', club: 'PSG', position: 'MID', value: 50 },
  { name: 'Warren Zaïre-Emery', club: 'PSG', position: 'MID', value: 60 },
  { name: 'Lee Kang-in', club: 'PSG', position: 'MID', value: 35 },
  { name: 'Senny Mayulu', club: 'PSG', position: 'MID', value: 25 },
  { name: 'Ousmane Dembélé', club: 'PSG', position: 'ATT', value: 90 },
  { name: 'Khvicha Kvaratskhelia', club: 'PSG', position: 'ATT', value: 90 },
  { name: 'Bradley Barcola', club: 'PSG', position: 'ATT', value: 75 },
  { name: 'Désiré Doué', club: 'PSG', position: 'ATT', value: 80 },
  { name: 'Gonçalo Ramos', club: 'PSG', position: 'ATT', value: 40 },

  // Bayern Munich
  { name: 'Manuel Neuer', club: 'Bayern Munich', position: 'GK', value: 4 },
  { name: 'Jonas Urbig', club: 'Bayern Munich', position: 'GK', value: 15 },
  { name: 'Sven Ulreich', club: 'Bayern Munich', position: 'GK', value: 1 },
  { name: 'Dayot Upamecano', club: 'Bayern Munich', position: 'DEF', value: 60 },
  { name: 'Kim Min-jae', club: 'Bayern Munich', position: 'DEF', value: 40 },
  { name: 'Josip Stanišić', club: 'Bayern Munich', position: 'DEF', value: 30 },
  { name: 'Alphonso Davies', club: 'Bayern Munich', position: 'DEF', value: 50 },
  { name: 'Sacha Boey', club: 'Bayern Munich', position: 'DEF', value: 25 },
  { name: 'Hiroki Itō', club: 'Bayern Munich', position: 'DEF', value: 25 },
  { name: 'Jonathan Tah', club: 'Bayern Munich', position: 'DEF', value: 35, note: "new '25" },
  { name: 'Joshua Kimmich', club: 'Bayern Munich', position: 'MID', value: 50 },
  { name: 'Leon Goretzka', club: 'Bayern Munich', position: 'MID', value: 25 },
  { name: 'Aleksandar Pavlović', club: 'Bayern Munich', position: 'MID', value: 50 },
  { name: 'João Palhinha', club: 'Bayern Munich', position: 'MID', value: 45 },
  { name: 'Michael Olise', club: 'Bayern Munich', position: 'MID', value: 90 },
  { name: 'Serge Gnabry', club: 'Bayern Munich', position: 'MID', value: 30 },
  { name: 'Konrad Laimer', club: 'Bayern Munich', position: 'MID', value: 30 },
  { name: 'Harry Kane', club: 'Bayern Munich', position: 'ATT', value: 100 },
  { name: 'Jamal Musiala', club: 'Bayern Munich', position: 'ATT', value: 140 },
  { name: 'Kingsley Coman', club: 'Bayern Munich', position: 'ATT', value: 45 },
  { name: 'Luis Díaz', club: 'Bayern Munich', position: 'ATT', value: 70, note: "new '25" },
];

const slug = (s: string) =>
  s
    .normalize('NFD')
    .replace(/[̀-ͯ]/g, '')
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/(^-|-$)/g, '');

export const PLAYERS: Player[] = RAW.map((p) => ({
  ...p,
  id: `${slug(p.club)}__${slug(p.name)}`,
}));

export const POSITION_LABEL: Record<Position, string> = {
  GK: 'Goalkeeper',
  DEF: 'Defender',
  MID: 'Midfielder',
  ATT: 'Attacker',
};
